[package]
name = "meituan-rs"
version = "0.7.0"
edition = "2021"

[[bin]]
name = "meituan-rs"
path = "src/main.rs"

[dependencies]
rand = "0.9"
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
r2d2 = "0.8"
r2d2_sqlite = "0.24"
chrono = "0.4"
log = "0.4"
env_logger = "0.11"
tungstenite = "0.29.0"
url = "2.5.8"
tokio = { version = "1", features = ["rt", "time"] }
ureq = { version = "3.3.0", features = ["json", "native-tls"] }

[target.'cfg(windows)'.dependencies]
tray-icon = "0.24.1"
windows-sys = { version = "0.59", features = ["Win32_System_Console", "Win32_Foundation", "Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader"] }

[build-dependencies]
chrono = "0.4"
